import io
from datetime import datetime
from docx import Document
from fpdf import FPDF

def filename(ext):
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"LegalEase_{ts}.{ext}"

def format_txt(content: str):
    return content

def format_docx(content: str):
    doc = Document()
    doc.add_heading("Legal Document - LegalEase AI", level=1)
    doc.add_paragraph(content)
    doc.add_paragraph("")
    p = doc.add_paragraph("Generated by LegalEase AI - Not legal advice")
    p.italic = True
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf

def format_pdf(content: str):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Legal Document - LegalEase AI", ln=True, align="C")
    pdf.ln(10)
    pdf.set_font("Arial", "", 11)
    # Clean content for latin-1
    safe_content = content.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 8, safe_content)
    pdf.ln(10)
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 10, "Generated by LegalEase AI - Not legal advice", ln=True)
    return bytes(pdf.output())
